version: '2'
services:

  web:
    extends:
      file: docker-compose-services.yml
      service: web
    image: matthiasg/nodejsdockerstarter-web:latest
    command: pm2-docker start bin/www
    depends_on:
      - db
    ports: #  Expose ports (HOST:CONTAINER)
      - "80:8000"
    environment:
      NODE_ENV: production

  db:
    extends:
      file: docker-compose-services.yml
      service: db

networks:
  all: