version: '2'
services:

  web:
    build: ./app/web
    expose: # Exposed ports, only be accessible to linked services (not by the host machine)
      - 8000
    networks:
      - all
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      MONGODB_URI: "mongodb://db:27017/app"

  db:
    image: mongo:3
    command: mongod --smallfiles
    expose:
      - 27017
    networks:
      - all

networks:
  all: